spring:
  profiles:
    active: @active-profiles@
  security:
    ignored: "/actuator/**"

server:
  port: 9000

keycloak:
  jwk: http://keycloak:8080/realms/Test/protocol/openid-connect/certs
#  jwk: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: INFO
      zalando:
        logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"